language: python
python:
  - "3.5"
# command to install dependencies
install: 
    - python setup.py install
    - "pip install -r requirements.txt"
    - pip install coveralls
script: 
    coverage run pytest
after_success:
    coveralls
